version: '2'

services:
  # PostgreSQL database
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/TranslationCaching-8699c192e59a.json
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "80:8000"
    links:
      - db
      - redis:redis
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - db
      - redis
    depends_on:
      - redis
