# Generated by Django 2.0 on 2017-12-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='label',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
